### ISSUE TITLE
Speed of the program

### ISSUE THREAD

**Issue by rxu2** [johnbarton/ACE#1]
How long will it take to fit an Ising model with 2,000 atoms?

Hmm. 10 atoms took much longer than 1 minute.

**Comment by johnbarton** [comment]
2000 spins is a large system, but the speed depends quite a lot on the properties of the Ising model. If the system is well-sampled and weakly correlated, then the inference will be much faster. If there are few samples or strong correlations/interactions, then it might take much longer.

I would expect that inference for a 10-site system should be fast, because that is small enough that the  entire partition function can be evaluated. Are the correlations in your system very strong, or nearly singular? Also, if you have not already done so I would recommend using regularization at least of the order of 1/# samples in the data used to generate the correlations. 

If you have questions about analysis of some specific data, I'd be happy to help out here or by email.

**Comment by rxu2** [comment]
Thank you for the kind offer. I wrote a program that can work for the hardware at my disposal.
